---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kubevirt-web-ui-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - namespaces
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - secrets
  - replicationcontrollers
  - serviceaccounts
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - oauth.openshift.io
  - project.openshift.io
  - template.openshift.io
  - route.openshift.io
  - apiextensions.k8s.io
  - kubevirt.io
  - extensions
  - apps
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
